name: Publish Package to npmjs

on:
  workflow_run:
    workflows: [Publish Release to GitHub]
    types: completed
    branches: main

jobs:
  publish:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci --no-audit --no-fund

      - run: npm run build

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
